package finalonWindows;

public enum SceneName {
    BARE, MAIN, SETTINGSMAIN, ADDTEMPLATE, EDITTEMPLATE, VIEWTEMPLATE, FORMULALIST, NUMBERFORMAT, TEMPLATESLIST, ADDREPORT, REPORTLIST, DEATHSCREEN, ADDINDUSTRY, LOGS, PRELOADER
}