package finalonWindows;

public enum SceneName {
    BARE, MAIN, SETTINGSMAIN, ADDTEMPLATE, EDITTEMPLATE, VIEWTEMPLATE, EDITFORMULAS, NUMBERFORMAT, TEMPLATESLIST, ADDREPORT, REPORTLIST, DEATHSCREEN,  LOGS, PRELOADER
}