package defaultData;

public enum EvaluationTypes {
    EVALUATE_END_ONLY,
    EVALUATE_EACH_PERIOD,
    EVALUATE_START_END_ONLY,
    GENERAL,
    PREFIX,
    SUFFIX,
    PERIOD_COMPARISON_INCREASE,
    PERIOD_COMPARISON_DECREASE,
    EACH_PERIOD_MULTIVARIATE,
    EACH_PERIOD_TRUE,
    ADDITIONAL_END_EVALUATION
}