package defaultData;

public enum EvaluationTypes {
    EVALUATE_END_ONLY, EVALUATE_EACH_PERIOD, GENERAL, PREFIX, SUFFIX, PERIOD_COMPARISON_INCREASE, PERIOD_COMPARISON_DECREASE, EACH_PERIOD_MULTIVARIATE, EACH_PERIOD_TRUE
}